version: 3.9
services:
  api:
    container_name: api
    build:
      context: ./api
      ports:
        - 8000:8000
      volumes:
        - ./api:/workspace:cached
  web:
    container_name: web
    build:
      context: ./web
      ports:
        - 3000:3000
      volumes:
        - ./web:/workspace:cached
      depends_on:
        - api